version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: scraper_db
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U your_username -d your_db_name"]
        interval: 10s
        timeout: 5s
        retries: 5
  web:
    build: .
    container_name: scraper
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - .:/app
    ports:
      - 8000:8000

volumes:
  postgres_data:
