# Generated by Django 5.2.7 on 2025-10-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(default='', max_length=200)),
                ('html_content', models.TextField()),
                ('text', models.TextField()),
                ('date', models.DateTimeField(db_comment='Date of publication')),
            ],
        ),
    ]
